[package]
name = "wasm_lifegame"
version = "0.1.0"
authors = ["furuhama <furuhama@users.noreply.github.com>"]

[dependencies]
wasm-bindgen = "0.2.4"

[profile.release]
# to debug wasm files
debug = true
